# Website name
title: '張淑微 老師 lab'

# Website URL
baseURL: 'https://example.com/'

############################
## LANGUAGE
############################

defaultContentLanguage: zh
hasCJKLanguage: true

############################
## BASIC SETTINGS
############################

enableEmoji: true
enableRobotsTXT: true

############################
## PAGINATION
############################

pagination:
  pagerSize: 10

############################
## OUTPUTS
############################

outputs:
  home: [HTML]
  section: [HTML]

############################
## TAXONOMY
############################

taxonomies:
  tag: tags
  publication_type: publication_types
  _merge: deep
