# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home 主頁
    url: /
    weight: 10
  - name: Introduction 簡介
    url: /
    weight: 11
  - name: News 最新消息
    url: /#news
    weight: 12
  - name: Patent 專利
    url: Patent/
    weight: 13
  - name: Papers 文獻
    url: /#papers
    weight: 14
  - name: Courses 課程
    url: courses/
    weight: 20
  - name: Members 成員
    url: /#members
    weight: 30
  
