# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home 主頁
    url: /
    weight: 10
  - name: Publications 
    url: publications/
    weight: 12
  - name: Courses 課程
    url: courses/
    weight: 13
  - name: Members 成員
    url: /members/
    weight: 14
  - name: Contact 
    url: Contact/
    weight: 15
